version: "3.9"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    networks:
      - localnet

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    networks:
      - localnet
    depends_on:
      - backend

networks:
  localnet:
    driver: bridge